Fix "NoMethodError: undefined method `each' for nil:NilClass"
This commit fixes the error that occurs at startup. It is caused
by calling `@polling_threads.each` in update_worker_count because
@polling_threads is assigned after run_worker_count_updater_thread
is called.